### PR TITLE
Cypress Test Scripts for Template Project 

### PR DESCRIPTION
**Pull request by Yemaneberhan-Lemma**
For Task [AXP -172](https://axelerant.atlassian.net/browse/AXP-172)
Pulled some test scripts from [previous efforts ](https://github.com/contrib-tracker/backend/pull/583)and made changes as needed and also added other new test scripts.

### CODE REVIEW

**Comment by zeshanziya** [comment]
@Yemaneberhan-Lemma few tests are failing. seems few missing dependencies.

**Comment by hussainweb** [comment]
@Yemaneberhan-Lemma, why are you not modifying the same PR? Secondly, wasn't the problem that the tests were correct but some fixes needed to be made to the site itself?

**Comment by hussainweb** [comment]
@Yemaneberhan-Lemma, this should be closed, right?

**Comment by Yemaneberhan-Lemma** [comment]
> @Yemaneberhan-Lemma, this should be closed, right?

Right.

**Pull request closed without merging**
