### PR TITLE
Trim added to fix the error related to variable cast

### PR DESCRIPTION
**Pull request by rishabjasrotia**
#351 

**Trim added to fix the error related to variable cast**

### CODE REVIEW

**Comment by hussainweb** [comment]
@rishabjasrotia, thanks. Shall we change this to use `plural` instead? https://www.drupal.org/node/2047135

**Comment by rishabjasrotia** [comment]
Yes @hussainweb I will make test with plural and update PR

**Comment by rishabjasrotia** [comment]
PR Updated!
cc @hussainweb

**Comment by hussainweb** [comment]
@rishabjasrotia, I am only getting back to addressing PRs here. Unfortunately, I can't see the logs for why `drupal_test` failed. Can you rebase or push new commits here so that there is another CI run?

**Pull request merged**
