### PR TITLE
fix: unset profile in core.extension

### PR DESCRIPTION
**Pull request by zeshanziya**

### CODE REVIEW

**Comment by hussainweb** [comment]
@zeshanziya, is this something that came up with `drush cex` or is this a manual edit?

**Comment by hussainweb** [comment]
I'm thinking that we should do the opposite. We should change `profile` to `null` instead of adding `standard`.

**Comment by zeshanziya** [comment]
> @zeshanziya, is this something that came up with `drush cex` or is this a manual edit?

It was a manual edit.

**Comment by zeshanziya** [comment]
> I'm thinking that we should do the opposite. We should change `profile` to `null` instead of adding `standard`.

Ok, I will update the code accordingly and push.

**Comment by zeshanziya** [comment]
@hussainweb I have updated the profile to null. Please review

**Comment by hussainweb** [comment]
Thanks, @zeshanziya. I see that the CI is reporting that everything is good. But did you try `drush cim` on local?

**Comment by zeshanziya** [comment]
> Thanks, @zeshanziya. I see that the CI is reporting that everything is good. But did you try `drush cim` on local?

Yes I ran `cim` and it worked without any issue.

**Review by hussainweb — APPROVED** [review]

**Pull request merged**
