### PR TITLE
Cypress: Added tests and updated config.js

### PR DESCRIPTION
**Pull request by KosalaiV**
- Added new tests
- Updated `config.j`s file
- Updated `support/e2e.js` file

### CODE REVIEW

**Comment by zeshanziya** [comment]
@KosalaiV few cypress tests are failing in CI. Can you please review and fix it.

**Comment by KosalaiV** [comment]
> @KosalaiV few cypress tests are failing in CI. Can you please review and fix it.

@zeshanziya Those are the expected failures.

**Comment by hussainweb** [comment]
@KosalaiV, I don't understand why the failures are expected. Are you saying that the site needs to be fixed?

**Comment by zeshanziya** [comment]
Below are fixed

> form-reset-button-check
> -- The reset button is not working as expected when an invalid name is entered. (Input "NonExistUser" in the name field and click "Apply". After clicking "Reset", the form does not reset as expected.)

This is Drupal's default behaviour and we can not change this. Drupal validates filters on reset button too. I have changed the test cases to check for validation message on entering wrong input.

> page-sublink-check
> -- The footer contains an inaccessible page: [plugin store](https://store.axelerant.com/), hence an error occurred.

Removed 404 links

> xss-check
> -- This is failing because the form has not been properly secured against XSS vulnerabilities.

Test case fixed.

@hussainweb Test are passing now. Please merge. then we can rebase @Yemaneberhan-Lemma PR #636 and work.

**Review by hussainweb — APPROVED** [review]

**Pull request merged**
