### PR TITLE
Eslint upgrades

### PR DESCRIPTION
**Pull request by hussainweb**
Manually upgrade dependencies because dependabot group is probably insufficient. In this case, we need to add `prettier` to the group to allow dependencies to be resolved.

### CODE REVIEW

**Comment by hussainweb** [comment]
This fails as Typescript eslint plugins don't support Eslint 9 yet. See https://github.com/typescript-eslint/typescript-eslint/issues/8211.

**Comment by AlviMurtaza** [comment]
Yes, the same was happening on my local as well, as I mentioned the dependencies are not supporting the latest version of eslint.

**Comment by hussainweb** [comment]
There is a new (alpha) version of typescript-eslint plugin that supports eslint v9. It's still alpha at this time and we can wait until there is a proper release.

**Comment by hussainweb** [comment]
Many of the dependencies from here are handled in other PRs. Now, only eslint is remaining once we have updates to typescript-eslint.

**Pull request closed without merging**
