### PR TITLE
Update package management from npm to yarn

### PR DESCRIPTION
**Pull request by zeshanziya**
Moved to yarn for faster dependency management.

### CODE REVIEW

**Comment by hussainweb** [comment]
@zeshanziya, is the difference between `npm` and `yarn` still that big to justify all this work? And if `npm` performance is not acceptable, how about looking into something like `bun`?

Also, tagging @AlviMurtaza for review.

**Comment by zeshanziya** [comment]
> @zeshanziya, is the difference between `npm` and `yarn` still that big to justify all this work? And if `npm` performance is not acceptable, how about looking into something like `bun`?
> 
> Also, tagging @AlviMurtaza for review.

@hussainweb , There's still a noticeable difference. We saw it in backstage. With `yarn.lock` and caching `node_modules` and `yarn` cache, `yarn install --frozen-lockfile` is very fast. I was learning how difficult it is to migrate to yarn from npm, I found the migration easy, so I raised this PR.

Regarding `bun`, it looks promising but it's still new. I am open to exploring `bun`.

**Comment by hussainweb** [comment]
There's a chance that you might find it easier to move from npm to bun rather than yarn. Anyway, my point was that the performance difference between npm and yarn is very small now for simple repos (Backstage is a multi-repo and maybe there it makes a difference).

Again, I am not opposed to yarn but I don't want to make a change just for the sake of doing it. And if we are pursuing performance, then we should definitely explore bun. It's almost a drop-in replacement (the package lock file is different).

**Comment by zeshanziya** [comment]
@hussainweb I tried Bun, and the migration was very straightforward. Thank you for the suggestion. We can definitely explore more about Bun. Do you think we should focus on it now or add it as an issue for later exploration?

**Comment by hussainweb** [comment]
I'd say later exploration. We want this project to be an example for other projects and I am concerned about this causing confusion.

**Review by AlviMurtaza — COMMENTED** [review]
As mentioned already by @hussainweb 

>  Anyway, my point was that the performance difference between npm and yarn is very small now for simple repos

I also agree to the fact that there isn't much difference in terms of performance for a simple repo between the two.

> I'd say later exploration. We want this project to be an example for other projects and I am concerned about this causing confusion. 

👍

**Comment by zeshanziya** [comment]
Closing this PR for now as we will evaluate the integration of Bun later. Please refer https://github.com/contrib-tracker/backend/issues/483

**Pull request closed without merging**
